<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
?>
<link rel="stylesheet" href="<?=$this->baseUrl('/assets/comments/styles.css')?>" xmlns="http://www.w3.org/1999/html"/>

<script>
    require.config({
        paths: {
            'comments': '/assets/comments'
        }
    });

    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid', 'comments/grid']);
</script>

<div id="comments" data-spy="grid" data-grid="<?=$grid->getUid()?>">

    <form class="form-search pull-left" action="<?=$this->url('comments', 'grid', ['comments-filter-status' => $statusFilter])?>" method="post">
        <select class="input-medium" name="comments-filter-alias">
            <option value="">All</option>
            <? foreach ($settingList as $setting) : ?>
                <option value="<?=$setting->alias?>"<?=((isset($settingFilterRow)) && $setting->alias == $settingFilterRow->alias) ? ' selected="selected"' : ''?>><?=$setting->alias?> (<?=$setting->total?>)</option>
            <? endforeach; ?>
        </select>
        <? if (isset($settingFilterRow)) : ?>
            <a href="<?=$this->url('comments', 'settings-crud', ['data' => ['id' => $settingFilterRow->id ]])?>" class="btn btn-small btn-success dialog" data-ajax-method="get">
        <? else : ?>
            <a href="#" class="btn btn-small btn-success disabled">
        <? endif; ?>
            <i class="icon-white icon-edit"></i>
        </a>

        <? if (isset($settingFilterRow)) : ?>
            <a href="<?=$this->url('comments', 'settings-remove', ['data' => ['id' => $settingFilterRow->id ]])?>" data-ajax-method="delete" class="btn btn-small ajax btn-danger remove-setting">
        <? else : ?>
            <a href="#" class="btn btn-small btn-danger disabled">
        <? endif; ?>
            <i class="icon-white icon-remove"></i>
        </a>
    </form>

    <div class="pull-left container-fluid">
        <a href="<?=$this->url('comments', 'settings-crud')?>" class="btn btn-primary dialog" data-ajax-method="get">
            <i class="icon-white icon-plus"></i> New Setting
        </a>
    </div>

    <div class="pagination pagination-right">
        <ul>
            <li><a href="#">Limit</a></li>
            <li <?=(($grid->getLimit()==5)?'class="active"':'')?>><a href="<?=$grid->limit(5)?>">5</a></li>
            <li <?=(($grid->getLimit()==10)?'class="active"':'')?>><a href="<?=$grid->limit(10)?>">10</a></li>
        </ul>
    </div>

    <ul class="nav nav-tabs">
        <li<?php echo $statusFilter == \Application\Comments\Content\Row::FILTER_ALL ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('alias', \Bluz\Grid\Grid::FILTER_EQ, (isset($settingFilterRow)) ? $settingFilterRow->alias : '', true)?>">All</a>
        </li>
        <li<?php echo $statusFilter == '' || $statusFilter == \Application\Comments\Content\Row::STATUS_APPROVED ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::STATUS_APPROVED, false)?>">Approved</a>
        </li>
        <li<?php echo $statusFilter == \Application\Comments\Content\Row::STATUS_PENDING ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::STATUS_PENDING, false)?>">Pending</a>
        </li>
        <li<?php echo $statusFilter == \Application\Comments\Content\Row::STATUS_SPAM ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::STATUS_SPAM, false)?>">Spam</a>
        </li>
        <li<?php echo $statusFilter == \Application\Comments\Content\Row::STATUS_DELETED ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::STATUS_DELETED, false)?>">Deleted</a>
        </li>
    </ul>

    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">

                <label for="select-all" class="checkbox pull-left">
                    <input type="checkbox" id="select-all" /> Select all
                </label>

                <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                <div class="btn-group pull-left">
                    <button class="btn btn-small disabled"
                        data-status="<?=\Application\Comments\Content\Row::STATUS_APPROVED?>"
                        <?= ($statusFilter == '' || $statusFilter == \Application\Comments\Content\Row::STATUS_APPROVED) ? ' disabled="disabled"' : ''?>
                        data-href="<?=$this->url(
                            'comments',
                            'change-status'
                        );?>">
                        <i class="icon-ok-circle"></i> Approve
                    </button>
                    <button class="btn btn-small disabled"
                        data-status="<?=\Application\Comments\Content\Row::STATUS_SPAM?>"
                        <?= $statusFilter == \Application\Comments\Content\Row::STATUS_SPAM ? ' disabled="disabled"' : ''?>
                        data-href="<?=$this->url(
                            'comments',
                            'change-status'
                        );?>">
                        <i class="icon-ban-circle"></i> Spam
                    </button>
                    <button class="btn btn-small disabled"
                        data-status="<?=\Application\Comments\Content\Row::STATUS_DELETED?>"
                        <?= $statusFilter == \Application\Comments\Content\Row::STATUS_DELETED ? ' disabled="disabled"' : ''?>
                        data-href="<?=$this->url(
                            'comments',
                            'change-status'
                        );?>">
                        <i class="icon-trash"></i> Delete
                    </button>
                </div>

                <!-- Search place -->
                <div class="nav-collapse collapse">
                    <form class="navbar-search pull-right">
                        <input type="text" class="search-query" placeholder="Search">
                    </form>
                </div>

            </div>
        </div>
    </div>

    <table class="table grid">
        <thead>
        <tr>
            <th class="select">&nbsp;</th>
            <th class="author"><a href="<?=$grid->order('login')?:'#'?>">Author</a></th>
            <th><a href="<?=$grid->order('created')?:'#'?>">Created</a></th>
            <th><a href="<?=$grid->order('content')?:'#'?>">Content</a></th>
            <? if($statusFilter == \Application\Comments\Content\Row::FILTER_ALL) : ?>
            <th class="status">Status</th>
            <? endif; ?>
            <th class="actions"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($grid->getData() as $row) : ?>
        <tr>
            <td class="select">
                <input type="checkbox" name="select" value="<?=$row['id']?>" data-status="<?= $row['status'] ?>"/>
            </td>
            <td class="author">
                <?=$this->widget('comments', 'gravatar', ['email' => $row['email']])?>
                <p>
                    <span><?=$row['login']?></span>
                </p>
                <span class="truncate" rel="tooltip" title="<?=$row['email']?>"><?=$row['email']?></span>
            </td>
            <td class="date"><?=$row['created']?></td>
            <td><?=$row['content']?></td>
            <? if($statusFilter == \Application\Comments\Content\Row::FILTER_ALL) : ?>
            <td>
                <?=$this->widget('comments', 'status', ['status' => $row['status']])?>
            </td>
            <? endif ?>
            <td class="controls">
                <div class="btn-group">

                    <a href="<?=$this->url(
                        'comments',
                        'change-status',
                        ['data' => [
                            'id' => $row['id'],
                            'status' => \Application\Comments\Content\Row::STATUS_APPROVED
                        ]]
                    );?>" data-ajax-method="get" class="btn btn-small ajax<?= $row['status'] == \Application\Comments\Content\Row::STATUS_APPROVED ? ' disabled' : ''?>">
                        <i class="icon-ok-circle"></i> Approve
                    </a>

                    <a href="<?=$this->url(
                        'comments',
                        'change-status',
                        ['data' => [
                            'id' => $row['id'],
                            'status' => \Application\Comments\Content\Row::STATUS_SPAM
                        ]]
                    );?>" data-ajax-method="get" class="btn btn-small ajax<?= $row['status'] == \Application\Comments\Content\Row::STATUS_SPAM ? ' disabled' : ''?>">
                        <i class="icon-ban-circle"></i> Spam
                    </a>

                    <a href="<?=$this->url(
                        'comments',
                        'change-status',
                        ['data' => [
                            'id' => $row['id'],
                            'status' => \Application\Comments\Content\Row::STATUS_DELETED
                        ]]
                    );?>" data-ajax-method="get" class="btn btn-small ajax<?= $row['status'] == \Application\Comments\Content\Row::STATUS_DELETED ? ' disabled' : ''?>">
                        <i class="icon-trash"></i> Delete
                    </a>
                </div>
            </td>
        </tr>
            <?php endforeach; ?>
        <?php if (sizeof($grid->getData()) < $grid->getLimit()) :
            $emptyRows = $grid->getLimit() - sizeof($grid->getData()); ?>
            <?php for ($i = 0; $i < $emptyRows; $i++): ?>
        <tr>
            <? if($statusFilter == \Application\Comments\Content\Row::FILTER_ALL) : ?>
            <td colspan="6">&nbsp;</td>
            <? else : ?>
            <td colspan="5">&nbsp;</td>
            <? endif; ?>
        </tr>
            <?php endfor; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination">
        <?php if ($grid->pages() > 1) : ?>
        <ul>
            <?php if ($prev = $grid->prev()) : ?><li><a href="<?=$prev?>">&laquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript:return false;">&laquo;</a></li>
            <?php endif; ?>


            <?php for ($page = 1; $page <= $grid->pages(); $page++) : ?>
            <li <?=($page==$grid->getPage()?'class="active"':'') ?>><a href="<?=$grid->page($page)?>"><?=$page?></a></li>
            <?php endfor; ?>

            <?php if ($next = $grid->next()) : ?><li><a href="<?=$next?>">&raquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript:return false;">&raquo;</a></li>
            <?php endif; ?>
        </ul>
        <?php endif; ?>

        <ul class="right">
            <li>
                <a href="<?=$grid->reset()?>">Total:
                    <strong><?=$grid->total()?></strong> <?=$this->__('record','records', $grid->total())?> on
                    <strong><?=$grid->pages()?></strong> <?=$this->__('page','pages', $grid->pages())?></a>
            </li>
        </ul>
    </div>

</div>
