<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
?>
<link rel="stylesheet" href="<?=$this->baseUrl('/assets/comments/styles.css')?>" />

<script>
    require.config({
        paths: {
            'comments': '/assets/comments'
        }
    });

    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid', 'comments/main']);
</script>

<div id="comments" data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <div class="pagination pagination-right">
        <ul>
            <li><a href="#">Limit</a></li>
            <li <?=(($grid->getLimit()==5)?'class="active"':'')?>><a href="<?=$grid->limit(5)?>">5</a></li>
            <li <?=(($grid->getLimit()==10)?'class="active"':'')?>><a href="<?=$grid->limit(10)?>">10</a></li>
        </ul>
    </div>

    <ul class="nav nav-tabs">
        <li<?php echo $filter == \Application\Comments\Content\Row::FILTER_ALL ? ' class="active"' : ''?>>
            <a href="<?=$this->url('comments', 'grid')?>">All</a>
        </li>
        <li<?php echo $filter == '' || $filter == \Application\Comments\Content\Row::FILTER_APPROVED ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::FILTER_APPROVED)?>">Approved</a>
        </li>
        <li<?php echo $filter == \Application\Comments\Content\Row::FILTER_PENDING ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::FILTER_PENDING)?>">Pending</a>
        </li>
        <li<?php echo $filter == \Application\Comments\Content\Row::FILTER_SPAM ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::FILTER_SPAM)?>">Spam</a>
        </li>
        <li<?php echo $filter == \Application\Comments\Content\Row::FILTER_DELETED ? ' class="active"' : ''?>>
            <a href="<?=$grid->filter('status', \Bluz\Grid\Grid::FILTER_EQ, \Application\Comments\Content\Row::FILTER_DELETED)?>">Deleted</a>
        </li>
    </ul>

    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">

                <label for="select-all" class="checkbox pull-left">
                    <input type="checkbox" id="select-all" /> Select all
                </label>

                <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                <div class="btn-group pull-left">
                    <button class="btn btn-small" disabled="disabled"><i class="icon-ok-circle"></i> Approve</button>
                    <button class="btn btn-small" disabled="disabled"><i class="icon-ban-circle"></i> Spam</button>
                    <button class="btn btn-small" disabled="disabled"><i class="icon-remove-circle"></i> Delete</button>
                </div>

                <!-- Everything you want hidden at 940px or less, place within here -->
                <div class="nav-collapse collapse">
                    <!-- .nav, .navbar-search, .navbar-form, etc -->

                    <form class="navbar-search pull-right">
                        <input type="text" class="search-query" placeholder="Search">
                    </form>
                </div>

            </div>
        </div>
    </div>

    <table class="table grid">
        <thead>
        <tr>
            <th class="select">&nbsp;</th>
            <th class="author"><a href="<?=$grid->order('login')?:'#'?>">Author</a></th>
            <th><a href="<?=$grid->order('created')?:'#'?>">Created</a></th>
            <th><a href="<?=$grid->order('content')?:'#'?>">Content</a></th>
            <th width="120px"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($grid->getData() as $row) : ?>
        <tr>
            <td class="select">
                <input type="checkbox" name="select" value="<?=$row['id']?>" />
            </td>
            <td class="author">
                <?=$this->widget('comments', 'gravatar', ['email' => $row['email']])?>
                <p>
                    <span><?=$row['login']?></span>
                </p>
                <span><?=$row['email']?></span>
            </td>
            <td class="date"><?=$row['created']?></td>
            <td><?=$row['content']?></td>
            <td class="controls">
                <div class="btn-group">

                    <a href="<?=$this->url('comments', 'approve', ['data' => ['id' => $row['id']]]);?>" class="btn btn-small dialog" data-ajax-method="get">
                        <i class="icon-ok-circle"></i> Approve
                    </a>

                    <a href="<?=$this->url('comments', 'spam', ['data' => ['id' => $row['id']]]);?>" class="btn btn-small dialog" data-ajax-method="get">
                        <i class="icon-ban-circle"></i> Spam
                    </a>

                    <a href="<?=$this->url('comments', 'delete', ['data' => ['id' => $row['id']]]);?>" class="btn btn-small dialog" data-ajax-method="get">
                        <i class="icon-remove-circle"></i> Delete
                    </a>
                </div>
            </td>
        </tr>
            <?php endforeach; ?>
        <?php if (sizeof($grid->getData()) < $grid->getLimit()) :
            $emptyRows = $grid->getLimit() - sizeof($grid->getData()); ?>
            <?php for ($i = 0; $i < $emptyRows; $i++): ?>
        <tr>
            <td colspan="5">&nbsp;</td>
        </tr>
            <?php endfor; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination">
        <?php if ($grid->pages() > 1) : ?>
        <ul>
            <?php if ($prev = $grid->prev()) : ?><li><a href="<?=$prev?>">&laquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript:return false;">&laquo;</a></li>
            <?php endif; ?>


            <?php for ($page = 1; $page <= $grid->pages(); $page++) : ?>
            <li <?=($page==$grid->getPage()?'class="active"':'') ?>><a href="<?=$grid->page($page)?>"><?=$page?></a></li>
            <?php endfor; ?>

            <?php if ($next = $grid->next()) : ?><li><a href="<?=$next?>">&raquo;</a></li>
            <?php else : ?> <li class="disabled"><a href="#" onclick="javascript:return false;">&raquo;</a></li>
            <?php endif; ?>
        </ul>
        <?php endif; ?>

        <ul class="right">
            <li>
                <a href="<?=$grid->reset()?>">Total:
                    <strong><?=$grid->total()?></strong> <?=$this->__('record','records', $grid->total())?> on
                    <strong><?=$grid->pages()?></strong> <?=$this->__('page','pages', $grid->pages())?></a>
            </li>
        </ul>
    </div>

</div>
